INSERT INTO beer(id, beer_name, brewer, date_received) VALUES (1, 'Sam Adams Lager','Virginia Beer Company','2005-12-09');
INSERT INTO beer(id, beer_name, brewer, date_received) VALUES (2, 'Saratoga Pale Ale','Saratoga','2005-02-14');
INSERT INTO beer(id, beer_name, brewer, date_received) VALUES (3, 'Sierra Nevada Pale Ale','Stones Throw Brewery','2007-05-14');
INSERT INTO beer(id, beer_name, brewer, date_received) VALUES (4, 'Liberty Bell Ale','Anchor Brewing Company','2006-12-29');
INSERT INTO beer(id, beer_name, brewer, date_received) VALUES (5, 'Guinness Stout','St. James Gate Brewery','2005-12-10');
INSERT INTO beer(id, beer_name, brewer, date_received) VALUES (55, 'Sweetwater 420','Sweetwater','2006-12-10');

INSERT INTO state (state, description) VALUES('AL','Alabama');
INSERT INTO state (state, description) VALUES('AK','Alaska');
INSERT INTO state (state, description) VALUES('AZ','Arizona');
INSERT INTO state (state, description) VALUES('AR','Arkansas');
INSERT INTO state (state, description) VALUES('CA','California');
INSERT INTO state (state, description) VALUES('CO','Colorado');
INSERT INTO state (state, description) VALUES('CT','Connecticut');
INSERT INTO state (state, description) VALUES('DE','Delaware');
INSERT INTO state (state, description) VALUES('DC','District of Columbia');
INSERT INTO state (state, description) VALUES('FL','Florida');
INSERT INTO state (state, description) VALUES('GA','Georgia');
INSERT INTO state (state, description) VALUES('GU','Guam');
INSERT INTO state (state, description) VALUES('HI','Hawaii');
INSERT INTO state (state, description) VALUES('ID','Idaho');
INSERT INTO state (state, description) VALUES('IL','Illinois');
INSERT INTO state (state, description) VALUES('IN','Indiana');
INSERT INTO state (state, description) VALUES('IA','Iowa');
INSERT INTO state (state, description) VALUES('KS','Kansas');
INSERT INTO state (state, description) VALUES('KY','Kentucky');
INSERT INTO state (state, description) VALUES('LA','Louisiana');
INSERT INTO state (state, description) VALUES('ME','Maine');
INSERT INTO state (state, description) VALUES('MD','Maryland');
INSERT INTO state (state, description) VALUES('MA','Massachusetts');
INSERT INTO state (state, description) VALUES('MI','Michigan');
INSERT INTO state (state, description) VALUES('MN','Minnesota');
INSERT INTO state (state, description) VALUES('MS','Mississippi');
INSERT INTO state (state, description) VALUES('MO','Missouri');
INSERT INTO state (state, description) VALUES('MT','Montana');
INSERT INTO state (state, description) VALUES('NE','Nebraska');
INSERT INTO state (state, description) VALUES('NV','Nevada');
INSERT INTO state (state, description) VALUES('NH','New Hampshire');
INSERT INTO state (state, description) VALUES('NJ','New Jersey');
INSERT INTO state (state, description) VALUES('NM','New Mexico');
INSERT INTO state (state, description) VALUES('NY','New York');
INSERT INTO state (state, description) VALUES('NC','North Carolina');
INSERT INTO state (state, description) VALUES('ND','North Dakota');
INSERT INTO state (state, description) VALUES('OH','Ohio');
INSERT INTO state (state, description) VALUES('OK','Oklahoma');
INSERT INTO state (state, description) VALUES('OR','Oregon');
INSERT INTO state (state, description) VALUES('PA','Pennsylvania');
INSERT INTO state (state, description) VALUES('PR','Puerto Rico');
INSERT INTO state (state, description) VALUES('RI','Rhode Island');
INSERT INTO state (state, description) VALUES('SC','South Carolina');
INSERT INTO state (state, description) VALUES('SD','South Dakota');
INSERT INTO state (state, description) VALUES('TN','Tennessee');
INSERT INTO state (state, description) VALUES('TX','Texas');
INSERT INTO state (state, description) VALUES('UT','Utah');
INSERT INTO state (state, description) VALUES('VT','Vermont');
INSERT INTO state (state, description) VALUES('VA','Virginia');
INSERT INTO state (state, description) VALUES('VI','Virgin Islands');
INSERT INTO state (state, description) VALUES('WA','Washington');
INSERT INTO state (state, description) VALUES('WV','West Virginia');
INSERT INTO state (state, description) VALUES('WI','Wisconsin');
INSERT INTO state (state, description) VALUES('WY','Wyoming');


INSERT INTO user(username, password) VALUES ('burke.cox','abc1234');
INSERT INTO user(username, password) VALUES ('pduvall','password');
INSERT INTO user(username, password) VALUES ('paul.duvall','password');
INSERT INTO user(username, password) VALUES ('verify','verify');