INSERT INTO beer(id, beer_name, brewer, date_received) VALUES (1, 'Sprecher Root Beer','Sprecher Brewery','2012-12-09');
INSERT INTO beer(id, beer_name, brewer, date_received) VALUES (2, 'Hanks Gourmet Root Beer','Hanks Gourmet Beverages','2013-02-19');
INSERT INTO beer(id, beer_name, brewer, date_received) VALUES (3, 'Dads Root Beer','Hedinger Brands LLC','2012-05-14');
INSERT INTO beer(id, beer_name, brewer, date_received) VALUES (4, 'Stewarts','Dr Pepper Snapple Group','2012-12-29');
INSERT INTO beer(id, beer_name, brewer, date_received) VALUES (5, 'Old Dominion Root Beer','Old Dominion Brewery','2012-11-02');
INSERT INTO beer(id, beer_name, brewer, date_received) VALUES (55, 'Hires','Dr Pepper Snapple Group','2012-06-18');

INSERT INTO state (state, description) VALUES('AL','Alabama');
INSERT INTO state (state, description) VALUES('AK','Alaska');
INSERT INTO state (state, description) VALUES('AZ','Arizona');
INSERT INTO state (state, description) VALUES('AR','Arkansas');
INSERT INTO state (state, description) VALUES('CA','California');
INSERT INTO state (state, description) VALUES('CO','Colorado');
INSERT INTO state (state, description) VALUES('CT','Connecticut');
INSERT INTO state (state, description) VALUES('DE','Delaware');
INSERT INTO state (state, description) VALUES('DC','District of Columbia');
INSERT INTO state (state, description) VALUES('FL','Florida');
INSERT INTO state (state, description) VALUES('GA','Georgia');
INSERT INTO state (state, description) VALUES('GU','Guam');
INSERT INTO state (state, description) VALUES('HI','Hawaii');
INSERT INTO state (state, description) VALUES('ID','Idaho');
INSERT INTO state (state, description) VALUES('IL','Illinois');
INSERT INTO state (state, description) VALUES('IN','Indiana');
INSERT INTO state (state, description) VALUES('IA','Iowa');
INSERT INTO state (state, description) VALUES('KS','Kansas');
INSERT INTO state (state, description) VALUES('KY','Kentucky');
INSERT INTO state (state, description) VALUES('LA','Louisiana');
INSERT INTO state (state, description) VALUES('ME','Maine');
INSERT INTO state (state, description) VALUES('MD','Maryland');
INSERT INTO state (state, description) VALUES('MA','Massachusetts');
INSERT INTO state (state, description) VALUES('MI','Michigan');
INSERT INTO state (state, description) VALUES('MN','Minnesota');
INSERT INTO state (state, description) VALUES('MS','Mississippi');
INSERT INTO state (state, description) VALUES('MO','Missouri');
INSERT INTO state (state, description) VALUES('MT','Montana');
INSERT INTO state (state, description) VALUES('NE','Nebraska');
INSERT INTO state (state, description) VALUES('NV','Nevada');
INSERT INTO state (state, description) VALUES('NH','New Hampshire');
INSERT INTO state (state, description) VALUES('NJ','New Jersey');
INSERT INTO state (state, description) VALUES('NM','New Mexico');
INSERT INTO state (state, description) VALUES('NY','New York');
INSERT INTO state (state, description) VALUES('NC','North Carolina');
INSERT INTO state (state, description) VALUES('ND','North Dakota');
INSERT INTO state (state, description) VALUES('OH','Ohio');
INSERT INTO state (state, description) VALUES('OK','Oklahoma');
INSERT INTO state (state, description) VALUES('OR','Oregon');
INSERT INTO state (state, description) VALUES('PA','Pennsylvania');
INSERT INTO state (state, description) VALUES('PR','Puerto Rico');
INSERT INTO state (state, description) VALUES('RI','Rhode Island');
INSERT INTO state (state, description) VALUES('SC','South Carolina');
INSERT INTO state (state, description) VALUES('SD','South Dakota');
INSERT INTO state (state, description) VALUES('TN','Tennessee');
INSERT INTO state (state, description) VALUES('TX','Texas');
INSERT INTO state (state, description) VALUES('UT','Utah');
INSERT INTO state (state, description) VALUES('VT','Vermont');
INSERT INTO state (state, description) VALUES('VA','Virginia');
INSERT INTO state (state, description) VALUES('VI','Virgin Islands');
INSERT INTO state (state, description) VALUES('WA','Washington');
INSERT INTO state (state, description) VALUES('WV','West Virginia');
INSERT INTO state (state, description) VALUES('WI','Wisconsin');
INSERT INTO state (state, description) VALUES('WY','Wyoming');


INSERT INTO user(username, password) VALUES ('student00','Student00!');
INSERT INTO user(username, password) VALUES ('student01','Student01!');
INSERT INTO user(username, password) VALUES ('student02','Student02!');
INSERT INTO user(username, password) VALUES ('student03','Student03!');
INSERT INTO user(username, password) VALUES ('student04','Student04!');
INSERT INTO user(username, password) VALUES ('student05','Student05!');
INSERT INTO user(username, password) VALUES ('student06','Student06!');
INSERT INTO user(username, password) VALUES ('student07','Student07!');
INSERT INTO user(username, password) VALUES ('student08','Student08!');
INSERT INTO user(username, password) VALUES ('student09','Student09!');
INSERT INTO user(username, password) VALUES ('student10','Student10!');
INSERT INTO user(username, password) VALUES ('student11','Student11!');
INSERT INTO user(username, password) VALUES ('student12','Student12!');
INSERT INTO user(username, password) VALUES ('student14','Student14!');
INSERT INTO user(username, password) VALUES ('student15','Student15!');
INSERT INTO user(username, password) VALUES ('student16','Student16!');
INSERT INTO user(username, password) VALUES ('student17','Student17!');
INSERT INTO user(username, password) VALUES ('student18','Student18!');
INSERT INTO user(username, password) VALUES ('student19','Student19!');
INSERT INTO user(username, password) VALUES ('student20','Student20!');
INSERT INTO user(username, password) VALUES ('pduvall','password');
INSERT INTO user(username, password) VALUES ('paul.duvall','password');
INSERT INTO user(username, password) VALUES ('verify','verify');